### ISSUE TITLE
Tag 2.3 Release 

### ISSUE THREAD

**Issue by mattt** [Jounce/Surge#128]
With Xcode 11 and Swift 5.1 now officially released, and with so many improvements and additions to the library, I think now would be a great time to cut a new minor release. 

@regexident Is there any work still pending that you'd like to include in 2.3?

**Comment by regexident** [comment]
The following test files I so far haven't "modernized":
- AuxiliaryTests.swift
- ConvolutionTests.swift
- HyperbolicTests.swift
- TrigonometricTests.swift

'ConvolutionTests.swift' looks fine to me, but 'HyperbolicTests.swift' and 'TrigonometricTests.swift' still have tests & benchmarks combined, which I would like to split up/clean up.

Other than that I think we're in a good shape for a 2.3 🙂.

**Comment by regexident** [comment]
@mattt With the issues of above comment fixed by now I'd say v2.3 is good to go. 👍

**Comment by mattt** [comment]
I think this is a great opportunity to revisit our release process. I don't want to hold things up too much, and maybe these are things that we can defer to 2.3.1 or 3.0, but here's what I'd like to see at some point:

- Automated CocoaPod trunk pushes from CI on tagged releases after tests pass (I've set this up in one of my other projects here: https://github.com/Flight-School/Money/blob/master/.travis.yml#L6-L10) 
- A changelog (`CHANGES.md`)
- Release notes (a la https://github.com/Jounce/Surge/releases/tag/2.1.0, though I'm not sure how this relates or can be derived automatically from a changelog)

@regexident Do you have strong opinions about any of these? Anything else you'd like us to incorporate as part of our release process?

**Comment by regexident** [comment]
👌 🎉 

---

In theory aggregating the release notes should result in the change log, but keeping an actual `CHANGES.md` file has the benefit of requiring pull requests (or changes in general) to leave a trace in that file before approval can be given. Additionally, unlike release notes you do not lose a changelog when moving from Github, i.e. less vendor lock-in.

As such `CHANGES.md` should be our source of truth, with release notes being an optional lossy and fragmented mirror of it.

---

>  […] though I'm not sure how this relates or can be derived automatically from a changelog)

If we were to use the https://keepachangelog.com/en/1.0.0/ "standard" for `CHANGES.md`, then we might be able to use a tool like [clparse](https://github.com/marcaddeo/clparse) (Rust; maintained; available via Homebrew) to parse the changelog, searching for a version entry matching the release tag and extract its information, optionally failing CI if nothing found.

Alternatively one could simply link from the release note to the corresponding section of `CHANGES.md` by using `…/CHANGELOG.md#100---2017-06-20` (i.e. 1.0.0 @ 2017-06-20).

I  have no experience with automating Github releases though, so just guessing.

---

All of this sounds like a good candidate for adding a `.github/PULL_REQUEST_TEMPLATE.md`?

- https://github.blog/2016-02-17-issue-and-pull-request-templates/

While we're at that we might as well add `.github/CONTRIBUTING.md` and `.github/ISSUE_TEMPLATE.md`.

- https://github.com/tylucaskelley/github-templates
- https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

**Comment by regexident** [comment]
> I think this is a great opportunity to revisit our release process. …

Github Actions? 🤔

**Comment by mattt** [comment]
> Github Actions? 🤔

😓 That's something I hadn't take into account before we spun the project out into its own org. Whereas I personally have access to the GitHub Actions preview, this new org doesn't (yet). I'll see if there's an easy way to request access.

**Comment by regexident** [comment]
For [**2.3.0**](https://github.com/Jounce/Surge/releases/tag/2.3.0) I opted to do things manually for now.

There are however a few actions that look like they could come in handy, most notably:

- [**Release Drafter**](https://github.com/marketplace/actions/release-drafter): Drafts your next release notes as pull requests are merged into master.

https://github.com/sdras/awesome-actions#pull-requests
