### ISSUE TITLE
is there some missing matrix functionality?

### ISSUE THREAD

**Issue by robbiemu** [Jounce/Surge#161]
I'm noticing in the documentation that for example we should be able to add a matrix with a scalar. so I would expect this to work:

```swift
    func sigmoid(x:Matrix<Double>) -> Matrix<Double> {
        return 1.0 / (Surge.exp(-1.0 * x) + 1.0)
    }
```

this produces the follwing error:
```swift
error: aside.xcplaygroundpage:20:43: error: binary operator '+' cannot be applied to operands of type 'Matrix<Double>' and 'Double'
        return 1.0 / (Surge.exp(-1.0 * x) + 1.0)
                      ~~~~~~~~~~~~~~~~~~~ ^ ~~~

aside.xcplaygroundpage:20:43: note: overloads for '+' exist with these partially matching parameter lists: (Date, TimeInterval), (DispatchTime, Double), (DispatchWallTime, Double), (Double, Double), (Matrix<Double>, Matrix<Double>), (Vector<Double>, Double)
        return 1.0 / (Surge.exp(-1.0 * x) + 1.0)
                                          ^
```

and here is where it says you can add a matrix and a scalar with a + infix operator: https://github.com/Jounce/Surge#addition

is this coming in a near future release? should the readme be upgraded to reflect _coming soon_ features?

**Comment by regexident** [comment]
Thanks for the report, @robbiemu!

I just updated the README to reflect the actual available APIs.

The `Matrix` API is currently somewhat limited, admittedly.  

However given the fact that Surge already provides >320 public functions, which all need to be manually maintained (and kept in sync with the README & unit tests, etc) I'm somewhat hesitant towards expanding it much further at this point (and am instead looking into alternative options for a more automated and code-gen-driven approach, which however is still in a very early and experimental stage).

In the meanwhile you can create an equivalent matrix via `Matrix(rows: …, columns: …, repeatedValue: 1.0)` and use `(Matrix, Matrix)` addition.

(cc @mattt)
