### ISSUE TITLE
Warning: "Inout expression creates a temporary pointer, but argument 'imagp' should be a pointer that outlives the call to 'init(realp:imagp:)'"

### ISSUE THREAD

**Issue by dme8a8** [Jounce/Surge#162]
Line _30_ **28** in FFT.swift `  var splitComplex = DSPSplitComplex(realp: &real, imagp: &imaginary)`

Now produces the following warning from Swift Compiler:

> Inout expression creates a temporary pointer, but argument 'imagp' should be a pointer that outlives the call to 'init(realp:imagp:)'

**Comment by mattt** [comment]
The line in question:

https://github.com/Jounce/Surge/blob/e5375a62be5bb84e7422e6a213e491bfd18e11c3/Sources/Surge/Digital%20Signal%20Processing/FFT.swift#L28

**Comment by dme8a8** [comment]
I'm sorry, it is line 28. I'm using the e5375a6 version.

**Comment by mattt** [comment]
Thanks for clarifying, @dme8a8. Updated the title to better reflect the issue.
