### ISSUE TITLE
missing power operator

### ISSUE THREAD

**Issue by robbiemu** [Jounce/Surge#163]
I note in the readme for the project here https://github.com/Jounce/Surge#power:
```
Operator
---
** (infix)
```

but with
```swift
    func test(_ x:Matrix<Double>) -> Matrix<Double> {
        return (x + 1.0) ** -1
    }
```

I get
```
error: aside.xcplaygroundpage:62:26: error: use of unresolved operator '**'
        return (x + 1.0) ** -1
                         ^~
```

I also note that in /Sources/Surge/Arithmetic/Arithmetic.swift I see the definitions for pow but not the operator.

This is similar to the previous issue (still open) that I raised, but now I am seeing that it is not just with addition, but in fact it seems like quite a lot of the readme documentation may not in fact be in place. Is there a private branch that has these?

**Comment by regexident** [comment]
Thanks for the report, @robbiemu!

I just opened a PR that addresses this omission.
