### ISSUE TITLE
Not working on Watch app

### ISSUE THREAD

**Issue by egon23** [Jounce/Surge#176]
I have added the library with SPM and set the target to WatchKit Extension. But still get the error: "Cannot find type 'NSString' in scope" from Matrix.swift
On iOS app works everything fine.

**Comment by BrettThePark** [comment]
This should be fixed once #177 is merged in

**Comment by mattt** [comment]
#177 is now merged and available as part of the 2.3.2 release. Thanks again for your help, @BrettThePark!

@egon23 Can you please confirm that this is fixed for you in the latest release?

**Comment by egon23** [comment]
yes it works perfectly now.👍
sorry for the late reply
