### ISSUE TITLE
some comfuse

### ISSUE THREAD

**Issue by TaoKai** [Jounce/Surge#179]

**Comment by TaoKai** [comment]
do I have some ways to realize a func like Numpy's where using Surge?

**Comment by regexident** [comment]
Hi @TaoKai,

Surge is a wrapper around Apple's Accelerate, which in turn [wraps a bunch of low-level APIs](https://developer.apple.com/documentation/accelerate), most notably:

- **vForce**: Functions for performing arithmetic and transcendental functions on vectors.
- **BLAS & LAPACK**: Libraries for performing linear algebra on sparse and dense matrices.

As such whether Surge is a good fit for you very much depends on the specific use-case.
Most low-level functions of Numpy, such as [`numpy.dot(a, b, out=None)`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) can be realized with Surge [as is](https://github.com/Jounce/Surge#dot-product), but with some of the more high-level ones you may have to code the last mile yourself.

Generally speaking Surge does not aim to be a Swift equivalent for Numpy, but rather a more ergonomic API for Accelerate.
