### ISSUE TITLE
DCT

### ISSUE THREAD

**Issue by kingslay** [Jounce/Surge#68]
do you plan support vDSP_DCT_Execute

**Comment by johndpope** [comment]
reference code by 
@IstuntRo  / @between40and2 
https://github.com/between40and2/ios-mastery/blob/42ca5fe6976b2cc9ac1ed1e03508efacbbe4b777/wwdc/7-coreos-sysfwk/accelerate/2018-701-1-vdsp.md

https://github.com/IstuntRo/Group-Conversation-Trascription/blob/60e5e337b70e54a0803a8f53c08751f01df8ccb0/asr_project/Helpers/MFCCComputer.swift
